<a href="https://colab.research.google.com/github/Deekshith0625/Machine_Learning/blob/main/PsyStyle_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [3]:
import os

PROJECT_DIR = "/content/drive/MyDrive/PsyStyle"

folders = [
    "models",
    "data",
    "data/polyvore",
    "data/psychology",
    "wardrobe",
    "backend",
    "frontend"
]

for folder in folders:
    os.makedirs(
        os.path.join(PROJECT_DIR, folder),
        exist_ok=True
    )

print("✅ PsyStyle project structure created")
print(PROJECT_DIR)

✅ PsyStyle project structure created
/content/drive/MyDrive/PsyStyle

In [ ]:
!pip install -q tensorflow pandas numpy matplotlib scikit-learn pillow opencv-python

In [4]:
import tensorflow as tf
import numpy as np
import pandas as pd
import sklearn
import cv2
from PIL import Image

print("TensorFlow:", tf.__version__)
print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)
print("OpenCV:", cv2.__version__)
print("✅ Environment ready")

TensorFlow: 2.20.0
NumPy: 2.1.3
Pandas: 2.2.3
OpenCV: 5.0.0
✅ Environment ready

In [6]:
import os
import shutil

os.makedirs("/root/.kaggle", exist_ok=True)

shutil.copy(
    "/content/kaggle.json",
    "/root/.kaggle/kaggle.json"
)

os.chmod(
    "/root/.kaggle/kaggle.json",
    0o600
)

print("✅ Kaggle configured successfully")

✅ Kaggle configured successfully

In [7]:
!mkdir -p /content/DeepFashion

!kaggle datasets download \
    -d vishalbsadanand/deepfashion-1 \
    -p /content/DeepFashion \
    --unzip

print("✅ DeepFashion loaded into Colab")

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/vishalbsadanand/deepfashion-1
License(s): unknown
Downloading deepfashion-1.zip to /content/DeepFashion
100% 5.70G/5.70G [01:00<00:00, 101MB/s]

✅ DeepFashion loaded into Colab

In [8]:
import os

DATASET_DIR = "/content/DeepFashion/datasets"

TRAIN_DIR = os.path.join(DATASET_DIR, "train_images")
TEST_DIR = os.path.join(DATASET_DIR, "test_images")

print("Train:", TRAIN_DIR)
print("Test:", TEST_DIR)
print("Train images:", len(os.listdir(TRAIN_DIR)))
print("Test images:", len(os.listdir(TEST_DIR)))

Train: /content/DeepFashion/datasets/train_images
Test: /content/DeepFashion/datasets/test_images
Train images: 10335
Test images: 1149

In [9]:
import os
import pandas as pd

def get_category(filename):
    name = filename.lower()

    if "denim" in name:
        return "Jeans"
    elif "tees_tanks" in name:
        return "T-Shirt"
    elif "blouses_shirts" in name:
        return "Shirt"
    elif "sweaters" in name:
        return "Sweater"
    elif "jackets_vests" in name:
        return "Jacket"
    elif "dresses" in name:
        return "Dress"
    elif "shorts" in name:
        return "Shorts"
    elif "graphic_tees" in name:
        return "Graphic T-Shirt"
    elif "shirts_polos" in name:
        return "Polo Shirt"
    elif "sweatshirts_hoodies" in name:
        return "Hoodie"
    elif "pants" in name:
        return "Trousers"
    elif "cardigans" in name:
        return "Cardigan"
    elif "skirts" in name:
        return "Skirt"
    elif "rompers_jumpsuits" in name:
        return "Romper"
    elif "jackets_coats" in name:
        return "Coat"
    elif "leggings" in name:
        return "Leggings"
    elif "suiting" in name:
        return "Suit"
    else:
        return "Unknown"


def create_dataframe(folder):

    records = []

    for filename in os.listdir(folder):

        if filename.lower().endswith(
            (".jpg", ".jpeg", ".png")
        ):

            category = get_category(filename)

            if category != "Unknown":

                records.append({
                    "image_path": os.path.join(
                        folder,
                        filename
                    ),
                    "category": category
                })

    return pd.DataFrame(records)


train_df = create_dataframe(TRAIN_DIR)
test_df = create_dataframe(TEST_DIR)

print("Training images:", len(train_df))
print("Testing images:", len(test_df))

print("\nTraining category distribution:")
print(train_df["category"].value_counts())

print("\nTesting category distribution:")
print(test_df["category"].value_counts())

Training images: 10335
Testing images: 1149

Training category distribution:
category
T-Shirt            2594
Dress              1959
Shirt              1377
Sweater             674
Shorts              612
Trousers            600
Romper              549
Coat                429
Cardigan            348
Skirt               340
Hoodie              265
Graphic T-Shirt     190
Jeans               146
Polo Shirt          103
Jacket               74
Leggings             67
Suit                  8
Name: count, dtype: int64

Testing category distribution:
category
T-Shirt            291
Dress              212
Shirt              149
Sweater             77
Shorts              76
Romper              63
Trousers            58
Skirt               44
Coat                40
Cardigan            33
Hoodie              32
Graphic T-Shirt     26
Jeans               15
Jacket              11
Polo Shirt          11
Leggings            11
Name: count, dtype: int64

In [10]:
FINAL_CATEGORIES = [
    "T-Shirt",
    "Dress",
    "Shirt",
    "Sweater",
    "Shorts",
    "Trousers",
    "Romper",
    "Jacket",
    "Skirt",
    "Cardigan",
    "Hoodie",
    "Jeans",
    "Leggings",
    "Suit"
]

train_df = train_df[
    train_df["category"].isin(FINAL_CATEGORIES)
].copy()

test_df = test_df[
    test_df["category"].isin(FINAL_CATEGORIES)
].copy()

class_names = FINAL_CATEGORIES

print("Final categories:", len(class_names))
print(class_names)

print("\nTraining images:", len(train_df))
print("Testing images:", len(test_df))

print("\nTraining distribution:")
print(train_df["category"].value_counts())

print("\nTesting distribution:")
print(test_df["category"].value_counts())

Final categories: 14
['T-Shirt', 'Dress', 'Shirt', 'Sweater', 'Shorts', 'Trousers', 'Romper', 'Jacket', 'Skirt', 'Cardigan', 'Hoodie', 'Jeans', 'Leggings', 'Suit']

Training images: 9613
Testing images: 1072

Training distribution:
category
T-Shirt     2594
Dress       1959
Shirt       1377
Sweater      674
Shorts       612
Trousers     600
Romper       549
Cardigan     348
Skirt        340
Hoodie       265
Jeans        146
Jacket        74
Leggings      67
Suit           8
Name: count, dtype: int64

Testing distribution:
category
T-Shirt     291
Dress       212
Shirt       149
Sweater      77
Shorts       76
Romper       63
Trousers     58
Skirt        44
Cardigan     33
Hoodie       32
Jeans        15
Jacket       11
Leggings     11
Name: count, dtype: int64

In [11]:
# CREATING TRAINIG AND VALIDATION DATA
import tensorflow as tf

IMG_SIZE = (224, 224)
BATCH_SIZE = 16
SEED = 123

train_paths = train_df["image_path"].values
train_labels = train_df["category"].map(
    {name: i for i, name in enumerate(class_names)}
).values

# Create TensorFlow dataset
full_train_dataset = tf.data.Dataset.from_tensor_slices(
    (train_paths, train_labels)
)

# Shuffle before splitting
full_train_dataset = full_train_dataset.shuffle(
    len(train_df),
    seed=SEED,
    reshuffle_each_iteration=False
)

total_size = len(train_df)
val_size = int(total_size * 0.2)

val_dataset = full_train_dataset.take(val_size)
train_dataset = full_train_dataset.skip(val_size)

print("Total training images:", total_size)
print("Training images:", total_size - val_size)
print("Validation images:", val_size)

Total training images: 9613
Training images: 7691
Validation images: 1922

In [12]:
# IMAGE PREPROCESSING
def load_and_preprocess_image(path, label):
    image = tf.io.read_file(path)
    image = tf.image.decode_image(
        image,
        channels=3,
        expand_animations=False
    )

    image = tf.image.resize(image, IMG_SIZE)
    image = tf.cast(image, tf.float32)
    image = tf.keras.applications.resnet50.preprocess_input(image)

    return image, label


train_dataset = train_dataset.map(
    load_and_preprocess_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

val_dataset = val_dataset.map(
    load_and_preprocess_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

train_dataset = train_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
val_dataset = val_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

print("✅ Image preprocessing completed")
print("Image size:", IMG_SIZE)
print("Batch size:", BATCH_SIZE)

✅ Image preprocessing completed
Image size: (224, 224)
Batch size: 16

In [13]:
base_model = tf.keras.applications.ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(224, 224, 3)
)

base_model.trainable = False

print("✅ ResNet50 loaded")
print("Trainable:", base_model.trainable)
print("Layers:", len(base_model.layers))

Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/resnet/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5
94765736/94765736 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
✅ ResNet50 loaded
Trainable: False
Layers: 175

In [14]:
model = tf.keras.Sequential([
    base_model,
    tf.keras.layers.GlobalAveragePooling2D(),
    tf.keras.layers.Dense(256, activation="relu"),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(len(class_names), activation="softmax")
])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ resnet50 (Functional)           │ (None, 7, 7, 2048)     │    23,587,712 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pooling2d        │ (None, 2048)           │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │       524,544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14)             │         3,598 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 24,115,854 (91.99 MB)

 Trainable params: 528,142 (2.01 MB)

 Non-trainable params: 23,587,712 (89.98 MB)

In [15]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("✅ Model compiled")

✅ Model compiled

In [16]:
history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=10
)

print("✅ First-stage training completed")

Epoch 1/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 130s 238ms/step - accuracy: 0.3942 - loss: 1.8150 - val_accuracy: 0.4844 - val_loss: 1.4835
Epoch 2/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 98s 203ms/step - accuracy: 0.4986 - loss: 1.4582 - val_accuracy: 0.5172 - val_loss: 1.3488
Epoch 3/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 139s 197ms/step - accuracy: 0.5401 - loss: 1.3187 - val_accuracy: 0.5442 - val_loss: 1.2769
Epoch 4/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 94s 195ms/step - accuracy: 0.5737 - loss: 1.2268 - val_accuracy: 0.5515 - val_loss: 1.2355
Epoch 5/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 143s 197ms/step - accuracy: 0.5982 - loss: 1.1502 - val_accuracy: 0.5676 - val_loss: 1.2096
Epoch 6/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 141s 196ms/step - accuracy: 0.6186 - loss: 1.0891 - val_accuracy: 0.5843 - val_loss: 1.1852
Epoch 7/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 92s 192ms/step - accuracy: 0.6396 - loss: 1.0330 - val_accuracy: 0.5952 - val_loss: 1.1655
Epoch 8/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 143s 195ms/step - accuracy: 0.6540 - loss: 0.9930 - val_accuracy: 0.5890 - val_loss: 1.1577
Epoch 9/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 141s 192ms/step - accuracy: 0.6772 - loss: 0.9427 - val_accuracy: 0.5983 - val_loss: 1.1510
Epoch 10/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 92s 191ms/step - accuracy: 0.6879 - loss: 0.9043 - val_accuracy: 0.6030 - val_loss: 1.1336
✅ First-stage training completed

In [17]:
base_model.trainable = True

# Freeze all ResNet50 layers except the last 20
for layer in base_model.layers[:-20]:
    layer.trainable = False

print("Total ResNet50 layers:", len(base_model.layers))
print(
    "Trainable ResNet50 layers:",
    sum(layer.trainable for layer in base_model.layers)
)

Total ResNet50 layers: 175
Trainable ResNet50 layers: 20

In [18]:
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

print("✅ Model recompiled for fine-tuning")

✅ Model recompiled for fine-tuning

In [19]:
fine_tune_history = model.fit(
    train_dataset,
    validation_data=val_dataset,
    epochs=10
)

print("✅ Fine-tuning completed")

Epoch 1/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 122s 219ms/step - accuracy: 0.6670 - loss: 0.9497 - val_accuracy: 0.6228 - val_loss: 1.0928
Epoch 2/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 123s 197ms/step - accuracy: 0.7709 - loss: 0.7069 - val_accuracy: 0.6301 - val_loss: 1.0735
Epoch 3/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 140s 193ms/step - accuracy: 0.8394 - loss: 0.5461 - val_accuracy: 0.6332 - val_loss: 1.0747
Epoch 4/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 145s 199ms/step - accuracy: 0.8925 - loss: 0.4098 - val_accuracy: 0.6337 - val_loss: 1.0848
Epoch 5/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 93s 193ms/step - accuracy: 0.9330 - loss: 0.2973 - val_accuracy: 0.6358 - val_loss: 1.1077
Epoch 6/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 97s 201ms/step - accuracy: 0.9645 - loss: 0.2012 - val_accuracy: 0.6405 - val_loss: 1.1595
Epoch 7/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 142s 201ms/step - accuracy: 0.9810 - loss: 0.1411 - val_accuracy: 0.6400 - val_loss: 1.1890
Epoch 8/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 140s 197ms/step - accuracy: 0.9895 - loss: 0.0952 - val_accuracy: 0.6384 - val_loss: 1.2486
Epoch 9/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 94s 195ms/step - accuracy: 0.9948 - loss: 0.0646 - val_accuracy: 0.6337 - val_loss: 1.2915
Epoch 10/10
481/481 ━━━━━━━━━━━━━━━━━━━━ 144s 201ms/step - accuracy: 0.9966 - loss: 0.0451 - val_accuracy: 0.6478 - val_loss: 1.3642
✅ Fine-tuning completed

In [20]:
MODEL_PATH = "/content/drive/MyDrive/PsyStyle/models/clothing_resnet50.keras"

model.save(MODEL_PATH)

print("✅ Clothing model saved")
print(MODEL_PATH)

✅ Clothing model saved
/content/drive/MyDrive/PsyStyle/models/clothing_resnet50.keras

In [24]:
feature_extractor = tf.keras.Sequential([
    model.layers[0],   # ResNet50
    model.layers[1]    # GlobalAveragePooling2D
])

print("✅ Feature extractor created")
print("Feature shape:", feature_extractor.output_shape)

✅ Feature extractor created
Feature shape: (None, 2048)

In [25]:
sample_path = train_df.iloc[0]["image_path"]

image = tf.io.read_file(sample_path)
image = tf.image.decode_image(
    image,
    channels=3,
    expand_animations=False
)

image = tf.image.resize(image, IMG_SIZE)
image = tf.cast(image, tf.float32)
image = tf.keras.applications.resnet50.preprocess_input(image)

image = tf.expand_dims(image, 0)

features = feature_extractor(image, training=False)

print("✅ Feature extraction works")
print("Feature shape:", features.shape)

✅ Feature extraction works
Feature shape: (1, 2048)

In [26]:
import pandas as pd

psychology_data = [
    # Happy
    ["Happy", "Extrovert", "Party", 8, "Dress", 0.95],
    ["Happy", "Extrovert", "Party", 7, "T-Shirt", 0.90],
    ["Happy", "Introvert", "College", 7, "Cardigan", 0.88],
    ["Happy", "Extrovert", "College", 9, "T-Shirt", 0.92],

    # Confident
    ["Confident", "Extrovert", "Interview", 9, "Suit", 0.98],
    ["Confident", "Introvert", "Interview", 8, "Shirt", 0.94],
    ["Confident", "Extrovert", "Interview", 8, "Blazer", 0.93],
    ["Confident", "Extrovert", "Party", 9, "Dress", 0.96],

    # Nervous
    ["Nervous", "Introvert", "Interview", 4, "Cardigan", 0.85],
    ["Nervous", "Introvert", "Interview", 3, "Shirt", 0.82],
    ["Nervous", "Extrovert", "College", 5, "Hoodie", 0.80],
    ["Nervous", "Introvert", "College", 4, "Sweater", 0.84],

    # Neutral
    ["Neutral", "Introvert", "College", 6, "Jeans", 0.90],
    ["Neutral", "Extrovert", "College", 7, "T-Shirt", 0.91],
    ["Neutral", "Introvert", "College", 6, "Trousers", 0.86],
    ["Neutral", "Extrovert", "Party", 6, "Shirt", 0.87],

    # Relaxed
    ["Relaxed", "Introvert", "College", 8, "Hoodie", 0.93],
    ["Relaxed", "Extrovert", "College", 8, "T-Shirt", 0.94],
    ["Relaxed", "Introvert", "Party", 7, "Sweater", 0.85],

    # Formal
    ["Confident", "Introvert", "Wedding", 9, "Suit", 0.97],
    ["Happy", "Extrovert", "Wedding", 9, "Dress", 0.96],
    ["Neutral", "Introvert", "Interview", 7, "Shirt", 0.92],
    ["Confident", "Extrovert", "Wedding", 8, "Dress", 0.94]
]

psychology_df = pd.DataFrame(
    psychology_data,
    columns=[
        "mood",
        "personality",
        "occasion",
        "confidence",
        "category",
        "compatibility"
    ]
)

print("✅ Psychology dataset created")
print("Rows:", len(psychology_df))
display(psychology_df)

✅ Psychology dataset created
Rows: 23

         mood personality   occasion  confidence  category  compatibility
0       Happy   Extrovert      Party           8     Dress           0.95
1       Happy   Extrovert      Party           7   T-Shirt           0.90
2       Happy   Introvert    College           7  Cardigan           0.88
3       Happy   Extrovert    College           9   T-Shirt           0.92
4   Confident   Extrovert  Interview           9      Suit           0.98
5   Confident   Introvert  Interview           8     Shirt           0.94
6   Confident   Extrovert  Interview           8    Blazer           0.93
7   Confident   Extrovert      Party           9     Dress           0.96
8     Nervous   Introvert  Interview           4  Cardigan           0.85
9     Nervous   Introvert  Interview           3     Shirt           0.82
10    Nervous   Extrovert    College           5    Hoodie           0.80
11    Nervous   Introvert    College           4   Sweater           0.84
12    Neutral   Introvert    College           6     Jeans           0.90
13    Neutral   Extrovert    College           7   T-Shirt           0.91
14    Neutral   Introvert    College           6  Trousers           0.86
15    Neutral   Extrovert      Party           6     Shirt           0.87
16    Relaxed   Introvert    College           8    Hoodie           0.93
17    Relaxed   Extrovert    College           8   T-Shirt           0.94
18    Relaxed   Introvert      Party           7   Sweater           0.85
19  Confident   Introvert    Wedding           9      Suit           0.97
20      Happy   Extrovert    Wedding           9     Dress           0.96
21    Neutral   Introvert  Interview           7     Shirt           0.92
22  Confident   Extrovert    Wedding           8     Dress           0.94

In [27]:
PSYCHOLOGY_PATH = "/content/drive/MyDrive/PsyStyle/data/psychology/psychology_dataset.csv"

psychology_df.to_csv(PSYCHOLOGY_PATH, index=False)

print("✅ Psychology dataset saved")
print(PSYCHOLOGY_PATH)

✅ Psychology dataset saved
/content/drive/MyDrive/PsyStyle/data/psychology/psychology_dataset.csv

In [28]:
!kaggle datasets list -s polyvore | head -20

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                 title                        size  lastUpdated                 downloadCount  voteCount  usabilityRating
----------------------------------  ---------------------  ----------  --------------------------  -------------  ---------  ---------------
nastaranganji/polyvore              polyvore                  8594704  2026-04-30 21:02:09.693000              5          0  0.1875
yiitcandeime/polyvore               polyvore               2525121973  2026-05-03 10:19:34.053000            100          0  0.23529412
firozkiresur/polyvore-metadata      polyvore-metadata         8584661  2026-02-11 05:52:48.317000             84          0  0.25
akshaypujari124/polyvore-images     Polyvore-Images        3435041618  2026-02-11 05:56:47.540000            166          0  0.25
nastaranganji/polyvore-tar-gz       polyvore.tar.gz           8584571  2026-05-11 14:41:35.690000              2          0  0.1875
nastaranganji/polyvore-image        polyvore.image         3440586880  2026-06-10 16:32:42.587000              4          0  0.1875
nastaranganji/re-polyvore           Re-PolyVore            3428945038  2026-07-29 17:13:09.263000              3          0  0.1875
firozkiresur/compatibilty-polyvore  compatibilty-polyvore     1412783  2026-02-17 06:33:44.867000             23          0  0.23529412

In [29]:
POLYVORE_DIR = "/content/polyvore"

!mkdir -p "$POLYVORE_DIR"

!kaggle datasets download \
    -d firozkiresur/polyvore-metadata \
    -p "$POLYVORE_DIR" \
    --unzip

print("✅ Polyvore metadata downloaded")

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/firozkiresur/polyvore-metadata
License(s): MIT
Downloading polyvore-metadata.zip to /content/polyvore
100% 8.19M/8.19M [00:00<00:00, 12.6MB/s]

✅ Polyvore metadata downloaded

In [30]:
import os

print("Polyvore files:\n")

for item in os.listdir("/content/polyvore"):
    path = os.path.join("/content/polyvore", item)

    if os.path.isfile(path):
        size_kb = os.path.getsize(path) / 1024
        print(f"📄 {item} — {size_kb:.1f} KB")
    else:
        print(f"📁 {item}")

Polyvore files:

📁 polyvore

In [31]:
POLYVORE_DATA_DIR = "/content/polyvore/polyvore"

print("Polyvore contents:\n")

for item in os.listdir(POLYVORE_DATA_DIR):
    path = os.path.join(POLYVORE_DATA_DIR, item)

    if os.path.isfile(path):
        size_kb = os.path.getsize(path) / 1024
        print(f"📄 {item} — {size_kb:.1f} KB")
    else:
        print(f"📁 {item}")

Polyvore contents:

📄 train_no_dup.json — 44665.5 KB
📄 fashion_compatibility_prediction.txt — 516.2 KB
📄 valid_no_dup.json — 3564.1 KB
📄 fill_in_blank_test.json — 1076.4 KB
📄 test_no_dup.json — 7310.8 KB

In [32]:
import json

POLYVORE_TRAIN = "/content/polyvore/polyvore/train_no_dup.json"

with open(POLYVORE_TRAIN, "r") as f:
    polyvore_train = json.load(f)

print("Type:", type(polyvore_train))
print("Number of records:", len(polyvore_train))

print("\nFirst record:")
print(polyvore_train[0])

Type: <class 'list'>
Number of records: 17316

First record:
{'name': 'Casual', 'views': 8743, 'items': [{'index': 1, 'name': 'mock neck embroidery suede sweatshirt', 'price': 24.0, 'likes': 10, 'image': 'http://img2.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=194508109', 'categoryid': 4495}, {'index': 2, 'name': 'luxe double zip hooded jacket', 'price': 150.0, 'likes': 2250, 'image': 'http://img2.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=188778349', 'categoryid': 25}, {'index': 3, 'name': 'citizens humanity high rise rocket hem jean', 'price': 248.0, 'likes': 2437, 'image': 'http://img1.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=188977857', 'categoryid': 27}, {'index': 4, 'name': 'suede tie short boots', 'price': 37.0, 'likes': 2, 'image': 'http://img1.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=194942557', 'categoryid': 261}, {'index': 5, 'name': 'cloth travel school backpack', 'price': 22.0, 'likes': 2, 'image': 'http://img2.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=194941874', 'categoryid': 259}, {'index': 6, 'name': '', 'price': 160.0, 'likes': 3, 'image': 'http://img1.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=194578327', 'categoryid': 1967}, {'index': 7, 'name': 'polyvore', 'price': -1, 'likes': 51, 'image': 'http://img2.polyvoreimg.com/cgi/img-thing?.out=jpg&size=m&tid=190204630', 'categoryid': 2}], 'image': 'http://ak1.polyvoreimg.com/cgi/img-set/cid/214181831/id/El8a99fQ5hG4HrPFO4xqOQ/size/y.jpg', 'likes': 394, 'date': 'One month', 'set_url': 'http://www.polyvore.com/casual/set?id=214181831', 'set_id': '214181831', 'desc': 'A fashion look from January 2017 by beebeely-look featuring Fuji, Citizens of Humanity, casual, casualoutfit, Packandgo, winterjacket and gearbest'}

In [33]:
from itertools import combinations
import pandas as pd

outfit_pairs = []

for outfit in polyvore_train:

    items = outfit.get("items", [])

    # Keep only items having a category
    items = [
        item for item in items
        if item.get("categoryid") is not None
    ]

    # Create all pairs of items in the same outfit
    for item1, item2 in combinations(items, 2):

        outfit_pairs.append({
            "set_id": outfit.get("set_id"),
            "item1_category": item1.get("categoryid"),
            "item2_category": item2.get("categoryid")
        })

polyvore_pairs_df = pd.DataFrame(outfit_pairs)

print("✅ Polyvore item pairs created")
print("Total pairs:", len(polyvore_pairs_df))

display(polyvore_pairs_df.head(10))

✅ Polyvore item pairs created
Total pairs: 339364

      set_id  item1_category  item2_category
0  214181831            4495              25
1  214181831            4495              27
2  214181831            4495             261
3  214181831            4495             259
4  214181831            4495            1967
5  214181831            4495               2
6  214181831              25              27
7  214181831              25             261
8  214181831              25             259
9  214181831              25            1967

In [34]:
# Collect all Polyvore category IDs and their item names

category_examples = {}

for outfit in polyvore_train:
    for item in outfit.get("items", []):
        category_id = item.get("categoryid")
        item_name = item.get("name", "")

        if category_id is not None and category_id not in category_examples:
            category_examples[category_id] = item_name

print("Number of unique Polyvore category IDs:",
      len(category_examples))

print("\nFirst 50 category IDs with examples:\n")

for category_id, name in list(category_examples.items())[:50]:
    print(category_id, "→", name)

Number of unique Polyvore category IDs: 363

First 50 category IDs with examples:

4495 → mock neck embroidery suede sweatshirt
25 → luxe double zip hooded jacket
27 → citizens humanity high rise rocket hem jean
261 → suede tie short boots
259 → cloth travel school backpack
1967 →
2 → polyvore
21 → nirvana distressed t-shirt
237 → rag bone rock w/ black skinny jeans
49 → vans authentic black mono trainers
106 → time low rubber bracelet hot topic
104 → monki singlet
37 → pre-owned chanel shoulder bag
55 → rag bone floppy brim fedora
11 → tops
28 → saint laurent zip cutout stretch nappa leather pants
65 → allurez square diamond halo engagement ring wedding band 14k gold
52 → lip buckled matte womens corset lip uk
200 → nude pink lipstick
186 → amazing eye makeup miss
76 → latest pro
236 → solid color long sleeve irregular blazer
9 → alice+olivia floral pattern a-line skirt
64 → gold boho turquoise leaf tassel earrings
62 → etro heart locket necklace
241 → mango skinny jane jegging
47 → sophia webster leather butterfly flats
196 → powder eye shadow deep sea ea
19 → isabel marant alpaca blend jumper
41 → alice light blue shoes flats leather sandals
38 → yoins beige leather-look gold-tone metal clutch bag shoulder strap
140 → elizabeth mini set
4438 →
8 → michelle mason women's suede wrap front mini skirt
222 → deborah lippmann creme nail polish
4 → valentino pleated cotton-blend dress
17 → valentino red ruffle detail blouse
24 → valentino wool-blend coat
43 → valentino rockstud metallic leather pumps
318 → valentino small striped leather satchel
105 → valentino printed cashmere silk scarf
58 → wild side mini hair
188 → bobbi brown peach
171 → set
18 → shein sheinside khaki long sleeve pockets loose cardigan sweater
46 → asos woven sandals
4428 → wildfox optical glasses
61 → monochrome watch
5 → michael kors sleeveless lace skirt dress
95 → marc jacobs rain splash eau de toilette

In [36]:
def map_polyvore_category(item_name):
    name = item_name.lower()

    # Specific categories first

    if any(x in name for x in [
        "hoodie", "sweatshirt"
    ]):
        return "Hoodie"

    elif any(x in name for x in [
        "jumpsuit", "romper"
    ]):
        return "Romper"

    elif any(x in name for x in [
        "suit"
    ]):
        return "Suit"

    elif any(x in name for x in [
        "cardigan"
    ]):
        return "Cardigan"

    elif any(x in name for x in [
        "legging"
    ]):
        return "Leggings"

    elif any(x in name for x in [
        "jean", "jeggings", "denim pants", "denim trouser"
    ]) and not any(x in name for x in [
        "jacket", "coat"
    ]):
        return "Jeans"

    elif any(x in name for x in [
        "jacket", "blazer", "coat"
    ]):
        return "Jacket"

    elif any(x in name for x in [
        "dress", "gown"
    ]):
        return "Dress"

    elif any(x in name for x in [
        "skirt"
    ]):
        return "Skirt"

    elif any(x in name for x in [
        "shorts"
    ]):
        return "Shorts"

    elif any(x in name for x in [
        "trouser", "pants", "chino"
    ]):
        return "Trousers"

    elif any(x in name for x in [
        "t-shirt", "tshirt", "tee", "tank top", "singlet"
    ]):
        return "T-Shirt"

    elif any(x in name for x in [
        "sweater", "jumper", "pullover", "knit"
    ]):
        return "Sweater"

    elif any(x in name for x in [
        "blouse", "shirt", "polo"
    ]):
        return "Shirt"

    return None


# Rebuild Polyvore clothing dataset
polyvore_items = []

for outfit in polyvore_train:

    for item in outfit.get("items", []):

        item_name = item.get("name", "")
        category = map_polyvore_category(item_name)

        if category is not None:
            polyvore_items.append({
                "set_id": outfit.get("set_id"),
                "item_name": item_name,
                "category": category
            })

polyvore_items_df = pd.DataFrame(polyvore_items)

print("✅ Corrected Polyvore clothing dataset")
print("Total clothing items:", len(polyvore_items_df))

print("\nCategory distribution:")
print(polyvore_items_df["category"].value_counts())

✅ Corrected Polyvore clothing dataset
Total clothing items: 31809

Category distribution:
category
Jacket      5696
Jeans       4609
Dress       4211
Skirt       3211
Sweater     2939
T-Shirt     2909
Shirt       2450
Trousers    1799
Shorts      1665
Hoodie       858
Cardigan     544
Leggings     541
Suit         264
Romper       113
Name: count, dtype: int64

In [37]:
# Build category-level outfit compatibility from Polyvore

categories = [
    "T-Shirt",
    "Dress",
    "Shirt",
    "Sweater",
    "Shorts",
    "Trousers",
    "Romper",
    "Jacket",
    "Skirt",
    "Cardigan",
    "Hoodie",
    "Jeans",
    "Leggings",
    "Suit"
]

compatibility_matrix = pd.DataFrame(
    0,
    index=categories,
    columns=categories,
    dtype=int
)

for set_id, group in polyvore_items_df.groupby("set_id"):

    outfit_categories = list(set(group["category"]))

    # Keep only our DeepFashion categories
    outfit_categories = [
        c for c in outfit_categories
        if c in categories
    ]

    # Count every pair appearing in the same outfit
    for i in range(len(outfit_categories)):
        for j in range(i + 1, len(outfit_categories)):

            c1 = outfit_categories[i]
            c2 = outfit_categories[j]

            compatibility_matrix.loc[c1, c2] += 1
            compatibility_matrix.loc[c2, c1] += 1

print("✅ Polyvore compatibility matrix created")
print("Matrix shape:", compatibility_matrix.shape)

display(compatibility_matrix)

✅ Polyvore compatibility matrix created
Matrix shape: (14, 14)

,T-Shirt,Dress,Shirt,Sweater,Shorts,Trousers,Romper,Jacket,Skirt,Cardigan,Hoodie,Jeans,Leggings,Suit
T-Shirt,0,167,173,159,388,325,8,897,414,106,94,1114,109,18
Dress,167,0,78,107,24,98,2,1152,62,104,27,139,24,22
Shirt,173,78,0,128,241,418,3,824,600,64,16,845,51,28
Sweater,159,107,128,0,175,357,2,1042,707,57,46,1059,112,10
Shorts,388,24,241,175,0,37,0,318,19,63,94,45,5,23
Trousers,325,98,418,357,37,0,2,732,54,41,105,94,11,22
Romper,8,2,3,2,0,2,0,41,1,1,0,2,0,1
Jacket,897,1152,824,1042,318,732,41,0,1030,39,188,1727,158,57
Skirt,414,62,600,707,19,54,1,1030,0,99,102,65,10,37
Cardigan,106,104,64,57,63,41,1,39,99,0,10,167,18,9
Hoodie,94,27,16,46,94,105,0,188,102,10,0,334,80,3
Jeans,1114,139,845,1059,45,94,2,1727,65,167,334,0,16,36
Leggings,109,24,51,112,5,11,0,158,10,18,80,16,0,5
Suit,18,22,28,10,23,22,1,57,37,9,3,36,5,0

In [38]:
# Normalize Polyvore compatibility scores to 0-1

compatibility_scores = compatibility_matrix.astype(float).copy()

max_value = compatibility_scores.values.max()

if max_value > 0:
    compatibility_scores = compatibility_scores / max_value

print("✅ Compatibility scores normalized")
print("Range:",
      compatibility_scores.values.min(),
      "to",
      compatibility_scores.values.max())

display(compatibility_scores.round(3))

✅ Compatibility scores normalized
Range: 0.0 to 1.0

,T-Shirt,Dress,Shirt,Sweater,Shorts,Trousers,Romper,Jacket,Skirt,Cardigan,Hoodie,Jeans,Leggings,Suit
T-Shirt,0.000,0.097,0.100,0.092,0.225,0.188,0.005,0.519,0.240,0.061,0.054,0.645,0.063,0.010
Dress,0.097,0.000,0.045,0.062,0.014,0.057,0.001,0.667,0.036,0.060,0.016,0.080,0.014,0.013
Shirt,0.100,0.045,0.000,0.074,0.140,0.242,0.002,0.477,0.347,0.037,0.009,0.489,0.030,0.016
Sweater,0.092,0.062,0.074,0.000,0.101,0.207,0.001,0.603,0.409,0.033,0.027,0.613,0.065,0.006
Shorts,0.225,0.014,0.140,0.101,0.000,0.021,0.000,0.184,0.011,0.036,0.054,0.026,0.003,0.013
Trousers,0.188,0.057,0.242,0.207,0.021,0.000,0.001,0.424,0.031,0.024,0.061,0.054,0.006,0.013
Romper,0.005,0.001,0.002,0.001,0.000,0.001,0.000,0.024,0.001,0.001,0.000,0.001,0.000,0.001
Jacket,0.519,0.667,0.477,0.603,0.184,0.424,0.024,0.000,0.596,0.023,0.109,1.000,0.091,0.033
Skirt,0.240,0.036,0.347,0.409,0.011,0.031,0.001,0.596,0.000,0.057,0.059,0.038,0.006,0.021
Cardigan,0.061,0.060,0.037,0.033,0.036,0.024,0.001,0.023,0.057,0.000,0.006,0.097,0.010,0.005
Hoodie,0.054,0.016,0.009,0.027,0.054,0.061,0.000,0.109,0.059,0.006,0.000,0.193,0.046,0.002
Jeans,0.645,0.080,0.489,0.613,0.026,0.054,0.001,1.000,0.038,0.097,0.193,0.000,0.009,0.021
Leggings,0.063,0.014,0.030,0.065,0.003,0.006,0.000,0.091,0.006,0.010,0.046,0.009,0.000,0.003
Suit,0.010,0.013,0.016,0.006,0.013,0.013,0.001,0.033,0.021,0.005,0.002,0.021,0.003,0.000

In [39]:
POLYVORE_COMPAT_PATH = (
    "/content/drive/MyDrive/PsyStyle/data/polyvore/"
    "polyvore_compatibility.csv"
)

compatibility_scores.to_csv(POLYVORE_COMPAT_PATH)

print("✅ Polyvore compatibility matrix saved")
print(POLYVORE_COMPAT_PATH)

✅ Polyvore compatibility matrix saved
/content/drive/MyDrive/PsyStyle/data/polyvore/polyvore_compatibility.csv

In [40]:
# FEATURE FUSION
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Load saved psychology dataset
psychology_df = pd.read_csv(
    "/content/drive/MyDrive/PsyStyle/data/psychology/psychology_dataset.csv"
)

# Encode categorical psychology features
encoder = OneHotEncoder(sparse_output=False)

categorical_features = encoder.fit_transform(
    psychology_df[["mood", "personality", "occasion"]]
)

# Normalize confidence from 1–10 to 0–1
confidence_feature = (
    psychology_df[["confidence"]].values / 10.0
)

# Combine all psychology features
psychology_features = np.concatenate(
    [categorical_features, confidence_feature],
    axis=1
)

print("✅ Psychology features prepared")
print("Feature shape:", psychology_features.shape)
print("Psychology samples:", len(psychology_df))

✅ Psychology features prepared
Feature shape: (23, 12)
Psychology samples: 23

In [41]:
# Psychology → clothing preference rules

psychology_rules = {

    "Interview": {
        "Formal": ["Shirt", "Trousers", "Jacket", "Suit", "Skirt"],
        "Casual": ["T-Shirt", "Jeans", "Hoodie"]
    },

    "Party": {
        "Formal": ["Dress", "Jacket", "Skirt", "Shirt"],
        "Casual": ["T-Shirt", "Jeans", "Jacket"]
    },

    "College": {
        "Formal": ["Shirt", "Trousers", "Cardigan"],
        "Casual": ["T-Shirt", "Jeans", "Hoodie", "Sweater"]
    },

    "Wedding": {
        "Formal": ["Dress", "Suit", "Jacket", "Skirt", "Shirt"],
        "Casual": ["Dress", "Shirt", "Jacket"]
    }
}

print("✅ Psychology recommendation rules created")
print("Occasions:", list(psychology_rules.keys()))

✅ Psychology recommendation rules created
Occasions: ['Interview', 'Party', 'College', 'Wedding']

In [42]:
def psychology_score(category, mood, personality, occasion, confidence):
    """
    Calculate how suitable a clothing category is
    for the user's psychological context.
    """

    score = 0.0

    # Occasion preference
    preferred_categories = []

    if occasion in psychology_rules:
        preferred_categories = (
            psychology_rules[occasion]["Formal"]
            + psychology_rules[occasion]["Casual"]
        )

    if category in preferred_categories:
        score += 0.50

    # Confidence effect
    if confidence >= 7:
        if category in ["Jacket", "Suit", "Shirt", "Dress"]:
            score += 0.20

    elif confidence <= 4:
        if category in ["Sweater", "Cardigan", "Hoodie", "T-Shirt"]:
            score += 0.15

    # Mood effect
    if mood == "Confident":
        if category in ["Jacket", "Suit", "Dress", "Shirt"]:
            score += 0.15

    elif mood == "Nervous":
        if category in ["Cardigan", "Sweater", "Hoodie", "T-Shirt"]:
            score += 0.15

    elif mood == "Happy":
        if category in ["Dress", "T-Shirt", "Skirt", "Jacket"]:
            score += 0.10

    # Personality effect
    if personality == "Introvert":
        if category in ["Cardigan", "Sweater", "Hoodie", "T-Shirt"]:
            score += 0.10

    elif personality == "Extrovert":
        if category in ["Jacket", "Dress", "Skirt", "Suit"]:
            score += 0.10

    return min(score, 1.0)


def polyvore_score(category1, category2):
    """
    Get normalized Polyvore compatibility
    between two clothing categories.
    """

    if category1 not in compatibility_scores.index:
        return 0.0

    if category2 not in compatibility_scores.columns:
        return 0.0

    return float(
        compatibility_scores.loc[category1, category2]
    )


print("✅ Recommendation scoring functions created")

✅ Recommendation scoring functions created

In [43]:
def recommend_outfit(
    wardrobe_categories,
    mood,
    personality,
    occasion,
    confidence
):
    results = []

    for category in wardrobe_categories:

        # Psychology score
        psych = psychology_score(
            category,
            mood,
            personality,
            occasion,
            confidence
        )

        # Find best Polyvore compatibility
        other_scores = []

        for other_category in wardrobe_categories:
            if other_category != category:
                score = polyvore_score(
                    category,
                    other_category
                )
                other_scores.append(score)

        if other_scores:
            polyvore = max(other_scores)
        else:
            polyvore = 0.0

        # Final score
        final_score = (
            0.60 * psych +
            0.40 * polyvore
        )

        results.append({
            "category": category,
            "psychology_score": psych,
            "polyvore_score": polyvore,
            "compatibility_score": final_score
        })

    results_df = pd.DataFrame(results)

    results_df = results_df.sort_values(
        "compatibility_score",
        ascending=False
    ).reset_index(drop=True)

    return results_df


print("✅ Final recommendation function created")

test_wardrobe = [
    "T-Shirt",
    "Jeans",
    "Jacket",
    "Sweater",
    "Trousers"
]

recommendations = recommend_outfit(
    wardrobe_categories=test_wardrobe,
    mood="Confident",
    personality="Extrovert",
    occasion="Interview",
    confidence=9
)

display(recommendations)

✅ Final recommendation function created

   category  psychology_score  polyvore_score  compatibility_score
0    Jacket              0.95        1.000000             0.970000
1     Jeans              0.50        1.000000             0.700000
2   T-Shirt              0.50        0.645049             0.558020
3  Trousers              0.50        0.423856             0.469543
4   Sweater              0.00        0.613202             0.245281

In [44]:
import zipfile
import os

wardrobe_dir = "/content/wardrobe"
os.makedirs(wardrobe_dir, exist_ok=True)

with zipfile.ZipFile("/content/PsyStyle_wardrobe.zip", "r") as zip_ref:
    zip_ref.extractall(wardrobe_dir)

print("✅ Wardrobe images loaded")

print(os.listdir(wardrobe_dir))

✅ Wardrobe images loaded
['jeans(1).jpg', 'hoodie(1).jpg', 'jacket(1).jpg', 'trouser(1).jpg', 'shirt(1).jpg']

In [45]:
import os
import numpy as np
import tensorflow as tf
import pandas as pd

wardrobe_dir = "/content/wardrobe"

results = []

for filename in os.listdir(wardrobe_dir):

    if filename.lower().endswith((".jpg", ".jpeg", ".png")):

        image_path = os.path.join(wardrobe_dir, filename)

        # Load image
        image = tf.keras.utils.load_img(
            image_path,
            target_size=(224, 224)
        )

        # Convert to array
        image_array = tf.keras.utils.img_to_array(image)

        # Normalize
        image_array = image_array / 255.0

        # Add batch dimension
        image_array = np.expand_dims(image_array, axis=0)

        # Predict
        predictions = model.predict(
            image_array,
            verbose=0
        )

        predicted_index = np.argmax(predictions[0])
        predicted_category = class_names[predicted_index]
        confidence = predictions[0][predicted_index]

        results.append({
            "image": filename,
            "predicted_category": predicted_category,
            "confidence": float(confidence)
        })

wardrobe_predictions = pd.DataFrame(results)

print("✅ Wardrobe images classified")
display(wardrobe_predictions)

✅ Wardrobe images classified

            image predicted_category  confidence
0    jeans(1).jpg              Dress    0.626201
1   hoodie(1).jpg              Dress    0.552701
2   jacket(1).jpg              Dress    0.571313
3  trouser(1).jpg              Dress    0.639862
4    shirt(1).jpg              Dress    0.572077

In [46]:
# Check top-5 predictions for each wardrobe image

for filename in os.listdir(wardrobe_dir):

    if filename.lower().endswith((".jpg", ".jpeg", ".png")):

        image_path = os.path.join(wardrobe_dir, filename)

        image = tf.keras.utils.load_img(
            image_path,
            target_size=(224, 224)
        )

        image_array = tf.keras.utils.img_to_array(image)
        image_array = image_array / 255.0
        image_array = np.expand_dims(image_array, axis=0)

        predictions = model.predict(image_array, verbose=0)[0]

        top5_indices = np.argsort(predictions)[-5:][::-1]

        print("\n", filename)

        for index in top5_indices:
            print(
                f"{class_names[index]:15s} "
                f"{predictions[index] * 100:.2f}%"
            )

 jeans(1).jpg
Dress           62.62%
Romper          7.68%
Shirt           5.74%
T-Shirt         4.83%
Trousers        4.82%

 hoodie(1).jpg
Dress           55.27%
Romper          8.43%
Shirt           7.65%
T-Shirt         6.32%
Trousers        5.46%

 jacket(1).jpg
Dress           57.13%
Romper          10.65%
Shirt           6.36%
Trousers        5.37%
Sweater         4.76%

 trouser(1).jpg
Dress           63.99%
Romper          7.51%
Shirt           6.09%
Trousers        4.40%
T-Shirt         4.23%

 shirt(1).jpg
Dress           57.21%
Romper          8.26%
Shirt           7.02%
T-Shirt         5.93%
Trousers        5.03%

In [47]:
# Test the trained model on images from its own validation dataset

batch_images, batch_labels = next(iter(val_dataset))

predictions = model.predict(batch_images, verbose=0)

predicted_labels = np.argmax(predictions, axis=1)

accuracy = np.mean(predicted_labels == batch_labels.numpy())

print("Validation batch accuracy:", round(accuracy * 100, 2), "%")

print("\nFirst 10 validation predictions:")

for i in range(min(10, len(batch_labels))):
    actual = class_names[batch_labels[i].numpy()]
    predicted = class_names[predicted_labels[i]]

    print(
        f"{i+1}. Actual: {actual:12s} | "
        f"Predicted: {predicted:12s} | "
        f"Confidence: {predictions[i][predicted_labels[i]] * 100:.2f}%"
    )

Validation batch accuracy: 62.5 %

First 10 validation predictions:
1. Actual: T-Shirt      | Predicted: T-Shirt      | Confidence: 85.11%
2. Actual: T-Shirt      | Predicted: Trousers     | Confidence: 95.05%
3. Actual: Shirt        | Predicted: Skirt        | Confidence: 80.16%
4. Actual: Shorts       | Predicted: Shorts       | Confidence: 93.63%
5. Actual: T-Shirt      | Predicted: T-Shirt      | Confidence: 54.17%
6. Actual: Romper       | Predicted: Dress        | Confidence: 64.33%
7. Actual: T-Shirt      | Predicted: T-Shirt      | Confidence: 85.60%
8. Actual: Dress        | Predicted: Dress        | Confidence: 70.92%
9. Actual: Shorts       | Predicted: T-Shirt      | Confidence: 71.80%
10. Actual: T-Shirt      | Predicted: T-Shirt      | Confidence: 98.29%

In [48]:
# Check how the training dataset images are represented

sample_images, sample_labels = next(iter(train_dataset))

print("Minimum pixel value:", sample_images[0].numpy().min())
print("Maximum pixel value:", sample_images[0].numpy().max())
print("Mean pixel value:", sample_images[0].numpy().mean())

print("\nImage shape:", sample_images[0].shape)

Minimum pixel value: -123.35859
Maximum pixel value: 140.09161
Mean pixel value: 70.039696

Image shape: (224, 224, 3)

In [49]:
from tensorflow.keras.applications.resnet50 import preprocess_input

results = []

for filename in os.listdir(wardrobe_dir):

    if filename.lower().endswith((".jpg", ".jpeg", ".png")):

        image_path = os.path.join(wardrobe_dir, filename)

        # Load image
        image = tf.keras.utils.load_img(
            image_path,
            target_size=(224, 224)
        )

        # Convert to array
        image_array = tf.keras.utils.img_to_array(image)

        # IMPORTANT:
        # Use the same preprocessing as ResNet50 training
        image_array = preprocess_input(image_array)

        # Add batch dimension
        image_array = np.expand_dims(image_array, axis=0)

        # Predict
        predictions = model.predict(
            image_array,
            verbose=0
        )[0]

        predicted_index = np.argmax(predictions)

        results.append({
            "image": filename,
            "predicted_category": class_names[predicted_index],
            "confidence": round(
                float(predictions[predicted_index]) * 100, 2
            )
        })

wardrobe_predictions = pd.DataFrame(results)

print("✅ Wardrobe images reclassified using correct ResNet50 preprocessing")
display(wardrobe_predictions)

✅ Wardrobe images reclassified using correct ResNet50 preprocessing

            image predicted_category  confidence
0    jeans(1).jpg              Dress       46.88
1   hoodie(1).jpg             Hoodie       96.16
2   jacket(1).jpg              Shirt       22.21
3  trouser(1).jpg              Shirt       45.69
4    shirt(1).jpg              Shirt       51.68

In [50]:
# Create PsyStyle wardrobe table

wardrobe_df = wardrobe_predictions.copy()

# Clean filenames for display
wardrobe_df["item"] = wardrobe_df["image"].str.replace(
    "(1)", "", regex=False
).str.replace(
    ".jpg", "", regex=False
)

# Convert model confidence to 0-1
wardrobe_df["confidence"] = wardrobe_df["confidence"] / 100.0

print("✅ PsyStyle wardrobe database created")

display(
    wardrobe_df[
        ["item", "image", "predicted_category", "confidence"]
    ]
)

✅ PsyStyle wardrobe database created

      item           image predicted_category  confidence
0    jeans    jeans(1).jpg              Dress      0.4688
1   hoodie   hoodie(1).jpg             Hoodie      0.9616
2   jacket   jacket(1).jpg              Shirt      0.2221
3  trouser  trouser(1).jpg              Shirt      0.4569
4    shirt    shirt(1).jpg              Shirt      0.5168

In [51]:
# Actual categories of the uploaded wardrobe items
# These are used as wardrobe metadata.

actual_categories = {
    "jeans": "Jeans",
    "hoodie": "Hoodie",
    "jacket": "Jacket",
    "trouser": "Trousers",
    "shirt": "Shirt"
}

wardrobe_df["actual_category"] = wardrobe_df["item"].map(
    actual_categories
)

print("✅ Actual wardrobe categories added")

display(
    wardrobe_df[
        [
            "item",
            "image",
            "predicted_category",
            "confidence",
            "actual_category"
        ]
    ]
)

✅ Actual wardrobe categories added

      item           image predicted_category  confidence actual_category
0    jeans    jeans(1).jpg              Dress      0.4688           Jeans
1   hoodie   hoodie(1).jpg             Hoodie      0.9616          Hoodie
2   jacket   jacket(1).jpg              Shirt      0.2221          Jacket
3  trouser  trouser(1).jpg              Shirt      0.4569        Trousers
4    shirt    shirt(1).jpg              Shirt      0.5168           Shirt

In [52]:
from itertools import combinations

# Create all unique clothing-item pairs
outfit_pairs = []

for i, j in combinations(wardrobe_df.index, 2):

    item1 = wardrobe_df.loc[i]
    item2 = wardrobe_df.loc[j]

    category1 = item1["actual_category"]
    category2 = item2["actual_category"]

    # Avoid same-category combinations
    if category1 != category2:

        outfit_pairs.append({
            "item1": item1["item"],
            "category1": category1,
            "item2": item2["item"],
            "category2": category2
        })

outfit_pairs_df = pd.DataFrame(outfit_pairs)

print("✅ Possible outfit combinations created")
print("Total combinations:", len(outfit_pairs_df))

display(outfit_pairs_df)

✅ Possible outfit combinations created
Total combinations: 10

     item1 category1    item2 category2
0    jeans     Jeans   hoodie    Hoodie
1    jeans     Jeans   jacket    Jacket
2    jeans     Jeans  trouser  Trousers
3    jeans     Jeans    shirt     Shirt
4   hoodie    Hoodie   jacket    Jacket
5   hoodie    Hoodie  trouser  Trousers
6   hoodie    Hoodie    shirt     Shirt
7   jacket    Jacket  trouser  Trousers
8   jacket    Jacket    shirt     Shirt
9  trouser  Trousers    shirt     Shirt

In [53]:
# Step 48: Calculate Polyvore compatibility for wardrobe pairs

def get_compatibility(category1, category2):
    score1 = compatibility_matrix.loc[category1, category2]
    score2 = compatibility_matrix.loc[category2, category1]

    return (score1 + score2) / 2


outfit_pairs_df["polyvore_score"] = outfit_pairs_df.apply(
    lambda row: get_compatibility(
        row["category1"],
        row["category2"]
    ),
    axis=1
)

print("✅ Polyvore compatibility scores calculated")

display(outfit_pairs_df)

✅ Polyvore compatibility scores calculated

     item1 category1    item2 category2  polyvore_score
0    jeans     Jeans   hoodie    Hoodie           334.0
1    jeans     Jeans   jacket    Jacket          1727.0
2    jeans     Jeans  trouser  Trousers            94.0
3    jeans     Jeans    shirt     Shirt           845.0
4   hoodie    Hoodie   jacket    Jacket           188.0
5   hoodie    Hoodie  trouser  Trousers           105.0
6   hoodie    Hoodie    shirt     Shirt            16.0
7   jacket    Jacket  trouser  Trousers           732.0
8   jacket    Jacket    shirt     Shirt           824.0
9  trouser  Trousers    shirt     Shirt           418.0

In [54]:
# Use the normalized Polyvore compatibility matrix

def get_compatibility(category1, category2):
    score1 = normalized_compatibility.loc[category1, category2]
    score2 = normalized_compatibility.loc[category2, category1]

    return (score1 + score2) / 2


outfit_pairs_df["polyvore_score"] = outfit_pairs_df.apply(
    lambda row: get_compatibility(
        row["category1"],
        row["category2"]
    ),
    axis=1
)

print("✅ Normalized Polyvore compatibility scores calculated")

display(outfit_pairs_df)

NameError: name 'normalized_compatibility' is not defined

In [55]:
# Create normalized Polyvore compatibility matrix

normalized_compatibility = (
    compatibility_matrix / compatibility_matrix.to_numpy().max()
)

print("✅ Normalized compatibility matrix created")
print(
    "Range:",
    normalized_compatibility.to_numpy().min(),
    "to",
    normalized_compatibility.to_numpy().max()
)

✅ Normalized compatibility matrix created
Range: 0.0 to 1.0

In [56]:
# Apply normalized Polyvore scores to wardrobe pairs

def get_compatibility(category1, category2):
    score1 = normalized_compatibility.loc[category1, category2]
    score2 = normalized_compatibility.loc[category2, category1]

    return (score1 + score2) / 2


outfit_pairs_df["polyvore_score"] = outfit_pairs_df.apply(
    lambda row: get_compatibility(
        row["category1"],
        row["category2"]
    ),
    axis=1
)

print("✅ Normalized Polyvore scores applied")

display(outfit_pairs_df)

✅ Normalized Polyvore scores applied

     item1 category1    item2 category2  polyvore_score
0    jeans     Jeans   hoodie    Hoodie        0.193399
1    jeans     Jeans   jacket    Jacket        1.000000
2    jeans     Jeans  trouser  Trousers        0.054430
3    jeans     Jeans    shirt     Shirt        0.489288
4   hoodie    Hoodie   jacket    Jacket        0.108859
5   hoodie    Hoodie  trouser  Trousers        0.060799
6   hoodie    Hoodie    shirt     Shirt        0.009265
7   jacket    Jacket  trouser  Trousers        0.423856
8   jacket    Jacket    shirt     Shirt        0.477128
9  trouser  Trousers    shirt     Shirt        0.242038

In [57]:
# Step 49: User psychology inputs

user_mood = "Confident"
user_personality = "Extrovert"
user_occasion = "Interview"
user_confidence = 8

print("✅ Psychology inputs selected")
print("Mood:", user_mood)
print("Personality:", user_personality)
print("Occasion:", user_occasion)
print("Confidence:", user_confidence)

✅ Psychology inputs selected
Mood: Confident
Personality: Extrovert
Occasion: Interview
Confidence: 8

In [58]:
# Step 50: Calculate psychology score for each outfit

def get_psychology_score(category1, category2):
    scores = []

    for category in [category1, category2]:
        if category in psychology_rules[user_occasion]:
            score = psychology_rules[user_occasion][category]
        else:
            score = 0.0

        scores.append(score)

    return sum(scores) / len(scores)


outfit_pairs_df["psychology_score"] = outfit_pairs_df.apply(
    lambda row: get_psychology_score(
        row["category1"],
        row["category2"]
    ),
    axis=1
)

print("✅ Psychology scores calculated")

display(
    outfit_pairs_df[
        [
            "item1",
            "category1",
            "item2",
            "category2",
            "polyvore_score",
            "psychology_score"
        ]
    ]
)

✅ Psychology scores calculated

     item1 category1    item2 category2  polyvore_score  psychology_score
0    jeans     Jeans   hoodie    Hoodie        0.193399               0.0
1    jeans     Jeans   jacket    Jacket        1.000000               0.0
2    jeans     Jeans  trouser  Trousers        0.054430               0.0
3    jeans     Jeans    shirt     Shirt        0.489288               0.0
4   hoodie    Hoodie   jacket    Jacket        0.108859               0.0
5   hoodie    Hoodie  trouser  Trousers        0.060799               0.0
6   hoodie    Hoodie    shirt     Shirt        0.009265               0.0
7   jacket    Jacket  trouser  Trousers        0.423856               0.0
8   jacket    Jacket    shirt     Shirt        0.477128               0.0
9  trouser  Trousers    shirt     Shirt        0.242038               0.0

In [59]:
print(psychology_rules)

{'Interview': {'Formal': ['Shirt', 'Trousers', 'Jacket', 'Suit', 'Skirt'], 'Casual': ['T-Shirt', 'Jeans', 'Hoodie']}, 'Party': {'Formal': ['Dress', 'Jacket', 'Skirt', 'Shirt'], 'Casual': ['T-Shirt', 'Jeans', 'Jacket']}, 'College': {'Formal': ['Shirt', 'Trousers', 'Cardigan'], 'Casual': ['T-Shirt', 'Jeans', 'Hoodie', 'Sweater']}, 'Wedding': {'Formal': ['Dress', 'Suit', 'Jacket', 'Skirt', 'Shirt'], 'Casual': ['Dress', 'Shirt', 'Jacket']}}

In [60]:
# Step 50B: Correct psychology scoring

formal_categories = set(
    psychology_rules[user_occasion]["Formal"]
)

casual_categories = set(
    psychology_rules[user_occasion]["Casual"]
)


def get_psychology_score(category1, category2):

    score1 = 1.0 if category1 in formal_categories else 0.0
    score2 = 1.0 if category2 in formal_categories else 0.0

    return (score1 + score2) / 2


outfit_pairs_df["psychology_score"] = outfit_pairs_df.apply(
    lambda row: get_psychology_score(
        row["category1"],
        row["category2"]
    ),
    axis=1
)

print("✅ Psychology scores corrected")

display(
    outfit_pairs_df[
        [
            "item1",
            "category1",
            "item2",
            "category2",
            "polyvore_score",
            "psychology_score"
        ]
    ]
)

✅ Psychology scores corrected

     item1 category1    item2 category2  polyvore_score  psychology_score
0    jeans     Jeans   hoodie    Hoodie        0.193399               0.0
1    jeans     Jeans   jacket    Jacket        1.000000               0.5
2    jeans     Jeans  trouser  Trousers        0.054430               0.5
3    jeans     Jeans    shirt     Shirt        0.489288               0.5
4   hoodie    Hoodie   jacket    Jacket        0.108859               0.5
5   hoodie    Hoodie  trouser  Trousers        0.060799               0.5
6   hoodie    Hoodie    shirt     Shirt        0.009265               0.5
7   jacket    Jacket  trouser  Trousers        0.423856               1.0
8   jacket    Jacket    shirt     Shirt        0.477128               1.0
9  trouser  Trousers    shirt     Shirt        0.242038               1.0

In [61]:
# Step 51: Calculate final outfit score

outfit_pairs_df["final_score"] = (
    0.60 * outfit_pairs_df["polyvore_score"]
    + 0.40 * outfit_pairs_df["psychology_score"]
)

# Sort from best to worst
outfit_pairs_df = outfit_pairs_df.sort_values(
    "final_score",
    ascending=False
).reset_index(drop=True)

print("✅ Final outfit scores calculated")

display(
    outfit_pairs_df[
        [
            "item1",
            "category1",
            "item2",
            "category2",
            "polyvore_score",
            "psychology_score",
            "final_score"
        ]
    ]
)

✅ Final outfit scores calculated

,item1,category1,item2,category2,polyvore_score,psychology_score,final_score
0,jeans,Jeans,jacket,Jacket,1.000000,0.5,0.800000
1,jacket,Jacket,shirt,Shirt,0.477128,1.0,0.686277
2,jacket,Jacket,trouser,Trousers,0.423856,1.0,0.654314
3,trouser,Trousers,shirt,Shirt,0.242038,1.0,0.545223
4,jeans,Jeans,shirt,Shirt,0.489288,0.5,0.493573
5,hoodie,Hoodie,jacket,Jacket,0.108859,0.5,0.265316
6,hoodie,Hoodie,trouser,Trousers,0.060799,0.5,0.236479
7,jeans,Jeans,trouser,Trousers,0.054430,0.5,0.232658
8,hoodie,Hoodie,shirt,Shirt,0.009265,0.5,0.205559
9,jeans,Jeans,hoodie,Hoodie,0.193399,0.0,0.116039

In [62]:
# Step 52: Final PsyStyle recommendation

best_outfit = outfit_pairs_df.iloc[0]

print("🎯 PSYSTYLE RECOMMENDATION")
print("=" * 40)

print(f"Occasion      : {user_occasion}")
print(f"Mood          : {user_mood}")
print(f"Personality   : {user_personality}")
print(f"Confidence    : {user_confidence}/10")

print("\n👕 Recommended Outfit")
print(f"Item 1        : {best_outfit['item1']} ({best_outfit['category1']})")
print(f"Item 2        : {best_outfit['item2']} ({best_outfit['category2']})")

print("\n📊 Scores")
print(f"Polyvore      : {best_outfit['polyvore_score']:.3f}")
print(f"Psychology    : {best_outfit['psychology_score']:.3f}")
print(f"Final Score   : {best_outfit['final_score']:.3f}")

print("\n✅ Recommendation generated successfully")

🎯 PSYSTYLE RECOMMENDATION
========================================
Occasion      : Interview
Mood          : Confident
Personality   : Extrovert
Confidence    : 8/10

👕 Recommended Outfit
Item 1        : jeans (Jeans)
Item 2        : jacket (Jacket)

📊 Scores
Polyvore      : 1.000
Psychology    : 0.500
Final Score   : 0.800

✅ Recommendation generated successfully

In [63]:
# Step 53: Display Top 3 PsyStyle recommendations

top_3 = outfit_pairs_df.head(3).copy()

print("🎯 TOP 3 PSYSTYLE RECOMMENDATIONS")
print("=" * 50)

for i, (_, outfit) in enumerate(top_3.iterrows(), start=1):

    print(f"\n#{i}")
    print(
        f"{outfit['item1']} ({outfit['category1']}) + "
        f"{outfit['item2']} ({outfit['category2']})"
    )

    print(f"Polyvore Score : {outfit['polyvore_score']:.3f}")
    print(f"Psychology     : {outfit['psychology_score']:.3f}")
    print(f"Final Score    : {outfit['final_score']:.3f}")

🎯 TOP 3 PSYSTYLE RECOMMENDATIONS
==================================================

#1
jeans (Jeans) + jacket (Jacket)
Polyvore Score : 1.000
Psychology     : 0.500
Final Score    : 0.800

#2
jacket (Jacket) + shirt (Shirt)
Polyvore Score : 0.477
Psychology     : 1.000
Final Score    : 0.686

#3
jacket (Jacket) + trouser (Trousers)
Polyvore Score : 0.424
Psychology     : 1.000
Final Score    : 0.654

In [64]:
# Step 54: Prepare final recommendation data

final_recommendations = top_3[
    [
        "item1",
        "category1",
        "item2",
        "category2",
        "polyvore_score",
        "psychology_score",
        "final_score"
    ]
].copy()

# Add ranking
final_recommendations.insert(
    0,
    "rank",
    range(1, len(final_recommendations) + 1)
)

print("✅ Final recommendation table prepared")

display(final_recommendations)

✅ Final recommendation table prepared

,rank,item1,category1,item2,category2,polyvore_score,psychology_score,final_score
0,1,jeans,Jeans,jacket,Jacket,1.000000,0.5,0.800000
1,2,jacket,Jacket,shirt,Shirt,0.477128,1.0,0.686277
2,3,jacket,Jacket,trouser,Trousers,0.423856,1.0,0.654314

In [65]:
# Step 55A: Save the trained PsyStyle model

MODEL_PATH = "/content/psystyle_resnet50.keras"

model.save(MODEL_PATH)

print("✅ PsyStyle model saved")
print("Model path:", MODEL_PATH)

✅ PsyStyle model saved
Model path: /content/psystyle_resnet50.keras

In [1]:
# Step 55B: Save PsyStyle recommendation data

import os
import pickle

SAVE_DIR = "/content/psystyle_data"
os.makedirs(SAVE_DIR, exist_ok=True)

# Save category names
with open(f"{SAVE_DIR}/categories.pkl", "wb") as f:
    pickle.dump(categories, f)

# Save normalized compatibility matrix
with open(f"{SAVE_DIR}/normalized_compatibility.pkl", "wb") as f:
    pickle.dump(normalized_compatibility, f)

# Save psychology rules
with open(f"{SAVE_DIR}/psychology_rules.pkl", "wb") as f:
    pickle.dump(psychology_rules, f)

# Save final recommendation table
final_recommendations.to_pickle(
    f"{SAVE_DIR}/final_recommendations.pkl"
)

print("✅ PsyStyle supporting data saved")
print("📁 Location:", SAVE_DIR)

NameError: name 'categories' is not defined

In [2]:
import os

print("Checking Google Drive...")

for root, dirs, files in os.walk("/content/drive/MyDrive/PsyStyle"):
    for file in files:
        if file.endswith(".keras") or file.endswith(".h5"):
            print(os.path.join(root, file))

Checking Google Drive...

In [3]:
import os

path = "/content/drive/MyDrive/PsyStyle"

print("PsyStyle folder exists:", os.path.exists(path))

if os.path.exists(path):
    print("\nContents:")
    for item in os.listdir(path):
        print(item)

PsyStyle folder exists: False

In [4]:
import os

print("Checking /content for saved model files...\n")

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith((".keras", ".h5", ".hdf5")):
            print(os.path.join(root, file))

Checking /content for saved model files...